---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes


- name: "upgrade apt packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm", "build-essential", "python3.8"]
    state: latest
    

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present