# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
jobs:
  lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
             wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint 
      - run:
          name: lint
          command: |
            make lint
  
  push-docker-container:
    docker:
      - image: python:3.7-alpine3.11
        auth:
          username: mahmuuud
          password: $DOCKER_PWD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: install dependencies
          command: |
            apk add docker-cli
            pip3 install awscli


      - run:
          name: Build and push docker image
          command: |
            docker login --username mahmuuud --password $DOCKER_PWD
            docker login -u AWS -p $(aws ecr get-login-password --region eu-central-1) 919729618761.dkr.ecr.eu-central-1.amazonaws.com
            docker build -t test-capstone .
            docker tag test-capstone:latest 919729618761.dkr.ecr.eu-central-1.amazonaws.com/test-capstone:latest
            docker push 919729618761.dkr.ecr.eu-central-1.amazonaws.com/test-capstone:latest



workflows:
  main:
    jobs:
      - lint
      - push-docker-container:
          requires:
            - lint
